### ISSUE TITLE
Port to Flint

### ISSUE THREAD

**Issue by caseif** [caseif/TTT#22]
TTT v0.8.0 will see the plugin ported to the Flint framework. This issue tracks the progress on the porting process.

**Tasks:**
- [x] Finalize Flint's API
- [x] Port TTT to Flint
- [x] Integrate new features in Flint into TTT
- [x] Bug testing (in progress)
- [x] Finalize Bukkit implementation (FlintCommon and Steel)

**Current overall ETA:** Early October
